# Generated by Django 3.0.7 on 2020-07-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeclients',
            name='Code',
            field=models.CharField(db_index=True, max_length=3),
        ),
    ]
