# Generated by Django 3.0.7 on 2020-07-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('ClientID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Код')),
                ('ClientName', models.CharField(max_length=255, verbose_name='Наименование клиента')),
                ('ClientType', models.CharField(max_length=20, verbose_name='Тип клиента')),
                ('TotalLoans', models.DecimalField(decimal_places=0, max_digits=20, verbose_name='Всего задолженность')),
                ('Address', models.CharField(max_length=255, verbose_name='Адрес клиента')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
