# Generated by Django 3.0.7 on 2020-07-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ByAverageFl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Продукты')),
                ('Balance', models.FloatField(verbose_name='UZS')),
                ('Average', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ByAverageUl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Срок')),
                ('AverageUZS', models.FloatField(verbose_name='UZS')),
                ('AverageUSD', models.FloatField(verbose_name='USD')),
                ('AverageEUR', models.FloatField(verbose_name='EUR')),
                ('AverageJPY', models.FloatField(verbose_name='JPY')),
                ('TotalUZS', models.FloatField()),
                ('TotalUSD', models.FloatField()),
                ('TotalEUR', models.FloatField()),
                ('TotalJPY', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ByOverdueBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Филиал')),
                ('Balance', models.FloatField(verbose_name='Выданные')),
                ('Overdue', models.FloatField(verbose_name='Просрочка')),
                ('CountPr', models.FloatField(verbose_name='Количество')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ByPercentage',
            fields=[
                ('Numeral', models.IntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('Title', models.CharField(max_length=255, verbose_name='Коридор')),
                ('ULLongTerm', models.FloatField(verbose_name='Долгосрочные ЮЛ')),
                ('ULLongPart', models.FloatField(verbose_name='Доля, %')),
                ('ULShortTerm', models.FloatField(verbose_name='Краткосрочные ЮЛ')),
                ('ULShortPart', models.FloatField(verbose_name='Доля, %')),
                ('FLLongTerm', models.FloatField(verbose_name='Долгосрочные ФЛ')),
                ('FLLongPart', models.FloatField(verbose_name='Доля, %')),
                ('FLShortTerm', models.FloatField(verbose_name='Краткосрочные ФЛ')),
                ('FLShortPart', models.FloatField(verbose_name='Доля, %')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ByPercentageUL',
            fields=[
                ('Numeral', models.IntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('Title', models.CharField(max_length=255, verbose_name='Коридор')),
                ('TermLess2', models.FloatField(verbose_name='до 2-х лет')),
                ('PartLess2', models.FloatField(verbose_name='Доля, %')),
                ('TermLess5', models.FloatField(verbose_name='от 2-х до 5 лет')),
                ('PartLess5', models.FloatField(verbose_name='Доля, %')),
                ('TermLess7', models.FloatField(verbose_name='от 5-ти до 7 лет')),
                ('PartLess7', models.FloatField(verbose_name='Доля, %')),
                ('TermLess10', models.FloatField(verbose_name='от 7-ми до 10 лет')),
                ('PartLess10', models.FloatField(verbose_name='Доля, %')),
                ('TermMore10', models.FloatField(verbose_name='свыше 10 лет')),
                ('PartMore10', models.FloatField(verbose_name='Доля, %')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ByRetailProduct',
            fields=[
                ('Numeral', models.IntegerField(primary_key=True, serialize=False, verbose_name='№')),
                ('Title', models.CharField(max_length=255, verbose_name='Продукт')),
                ('PorBalans', models.FloatField(verbose_name='Кредитный портфель')),
                ('PorPercent', models.FloatField(verbose_name='Доля, %')),
                ('PrsBalans', models.FloatField(verbose_name='Просрочка ОД')),
                ('NplBalans', models.FloatField(verbose_name='NPL')),
                ('NplWeight', models.FloatField(verbose_name='Удельный вес')),
                ('NachBalans', models.FloatField(verbose_name='Просрочка по % (16377)')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ByTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Сроки')),
                ('PorBalans', models.FloatField(verbose_name='Кредитный портфель')),
                ('PorPercent', models.FloatField(verbose_name='Доля, %')),
                ('NplBalans', models.FloatField(verbose_name='NPL')),
                ('ToxBalans', models.FloatField(verbose_name='Токсичные кредиты')),
                ('AmountNTK', models.FloatField(verbose_name='ТК+NPL')),
                ('WeightNTK', models.FloatField(verbose_name='Удельный вес')),
                ('ResBalans', models.FloatField(verbose_name='Резервы')),
                ('ResCovers', models.FloatField(verbose_name='Покрытие резервами')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataByGeocode',
            fields=[
                ('Title', models.CharField(max_length=255)),
                ('GeoCode', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Balance', models.FloatField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfoCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Показатели')),
                ('Old_Value', models.CharField(max_length=255, verbose_name='Предыдущий  месяц')),
                ('New_Value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Текущий месяц')),
                ('Updates', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Изменение')),
                ('Percent', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Изменение, %')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NplClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(db_column='Numeral', verbose_name='№')),
                ('Name', models.CharField(max_length=255, verbose_name='Наименование заёмщика')),
                ('Branch', models.CharField(max_length=255, verbose_name='Филиал')),
                ('Balans', models.FloatField(verbose_name='Остаток кредита')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OverdueCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(db_column='Numeral', verbose_name='№')),
                ('Name', models.CharField(max_length=255, verbose_name='Наименование клиента')),
                ('Branch', models.CharField(max_length=255, verbose_name='Филиал')),
                ('Balans', models.FloatField(verbose_name='Остаток р/с 16377')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToxicCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(db_column='Numeral', verbose_name='№')),
                ('Name', models.CharField(max_length=255, verbose_name='Наименование клиента')),
                ('Branch', models.CharField(max_length=255, verbose_name='Филиал')),
                ('Balans', models.FloatField(verbose_name='Остаток р/с 16377')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
