# Generated by Django 3.0.6 on 2020-06-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMBER', models.IntegerField()),
                ('CODE_REG', models.CharField(max_length=25)),
                ('MFO', models.CharField(max_length=5)),
                ('NAME_CLIENT', models.CharField(max_length=255)),
                ('BALANS_SCHET', models.IntegerField()),
                ('CREDIT_SCHET', models.CharField(max_length=20)),
                ('DATE_RESHENIYA', models.CharField(max_length=25)),
                ('CODE_VAL', models.CharField(max_length=25)),
                ('SUM_DOG_NOM', models.DecimalField(decimal_places=2, max_digits=15)),
                ('SUM_DOG_EKV', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DATE_DOGOVOR', models.DateField()),
                ('DATE_FACTUAL', models.DateField()),
                ('DATE_POGASH', models.DateField()),
                ('SROK', models.CharField(max_length=25)),
                ('DOG_NUMBER_DATE', models.CharField(max_length=25)),
                ('CREDIT_PROCENT', models.IntegerField()),
                ('PROSR_PROCENT', models.IntegerField()),
                ('OSTATOK_CRED_SCHET', models.DecimalField(decimal_places=2, max_digits=15)),
                ('OSTATOK_PERESM', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DATE_PRODL', models.CharField(max_length=25)),
                ('DATE_POGASH_POSLE_PRODL', models.DateField()),
                ('OSTATOK_PROSR', models.DecimalField(decimal_places=2, max_digits=15)),
                ('DATE_OBRAZ_PROS', models.DateField()),
                ('OSTATOK_SUDEB', models.DecimalField(decimal_places=2, max_digits=15)),
                ('KOD_PRAVOXR_ORG', models.CharField(max_length=255)),
                ('PRIZNAK_RESHENIYA', models.CharField(max_length=255)),
                ('DATE_PRED_RESH', models.CharField(max_length=25)),
                ('VSEGO_ZADOLJENNOST', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CLASS_KACHESTVA', models.CharField(max_length=25)),
                ('OSTATOK_REZERV', models.DecimalField(decimal_places=2, max_digits=15)),
                ('OSTATOK_NACH_PRCNT', models.DecimalField(decimal_places=2, max_digits=15)),
                ('OSTATOK_NACH_PROSR_PRCNT', models.DecimalField(decimal_places=2, max_digits=15)),
                ('OCENKA_OBESPECHENIYA', models.DecimalField(decimal_places=2, max_digits=15)),
                ('OBESPECHENIE', models.CharField(max_length=255)),
                ('OPISANIE_OBESPECHENIE', models.CharField(max_length=255)),
                ('ISTOCHNIK_SREDTSVO', models.CharField(max_length=255)),
                ('VID_KREDITOVANIYA', models.CharField(max_length=255)),
                ('PURPOSE_CREDIT', models.CharField(max_length=255)),
                ('VISHEST_ORG_CLIENT', models.CharField(max_length=255)),
                ('OTRASL_KREDITOVANIYA', models.CharField(max_length=255)),
                ('OTRASL_CLIENTA', models.CharField(max_length=255)),
                ('CLASS_KREDIT_SPOS', models.CharField(max_length=255)),
                ('PREDSEDATEL_KB', models.CharField(max_length=255)),
                ('ADRESS_CLIENT', models.CharField(max_length=255)),
                ('UN_NUMBER_CONTRACT', models.CharField(max_length=255)),
                ('INN_PASSPORT', models.CharField(max_length=25)),
                ('OSTATOK_VNEB_PROSR', models.DecimalField(decimal_places=2, max_digits=15)),
                ('KONKR_NAZN_CREDIT', models.CharField(max_length=255)),
                ('BORROWER_TYPE', models.CharField(max_length=255)),
                ('SVYAZANNIY', models.IntegerField()),
                ('MALIY_BIZNES', models.IntegerField()),
                ('REGISTER_NUMBER', models.CharField(max_length=255)),
                ('OKED', models.CharField(max_length=255)),
                ('CODE_CONRACT', models.CharField(max_length=25)),
            ],
        ),
    ]
