# Generated by Django 3.0.7 on 2020-06-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
