# Generated by Django 3.0.6 on 2020-06-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REPORT_TITLE', models.CharField(max_length=255)),
                ('REPORT_MONTH', models.IntegerField()),
                ('REPORT_YEAR', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reportdata',
            name='REPORT',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='credits.ListReports'),
        ),
    ]
