# Generated by Django 3.0.6 on 2020-06-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20200604_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='listreports',
            name='DATE_CREATED',
            field=models.DateField(null=True),
        ),
    ]
