# Generated by Django 3.0.7 on 2020-07-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_branch_clienttype_currency_listreports_overduepercents_payments_reportdata_segment_tempdata_tempdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUMS', models.IntegerField(null=True)),
                ('NAME', models.CharField(max_length=255, null=True)),
                ('CODE', models.IntegerField(null=True)),
            ],
        ),
    ]
