# Generated by Django 3.0.7 on 2020-06-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20200630_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempdata',
            old_name='id',
            new_name='idX',
        ),
    ]
