# Generated by Django 3.0.7 on 2020-06-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_auto_20200630_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempdata',
            old_name='idX',
            new_name='id',
        ),
    ]
