# Generated by Django 3.0.7 on 2020-07-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_auto_20200718_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='DATE_VIDACHI',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
