# Generated by Django 3.0.6 on 2020-06-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_auto_20200604_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='BALANS_SCHET',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='CREDIT_PROCENT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='MALIY_BIZNES',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='NUMBER',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='PROSR_PROCENT',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='SVYAZANNIY',
            field=models.IntegerField(null=True),
        ),
    ]
