# Generated by Django 3.0.7 on 2020-07-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_auto_20200701_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdata',
            name='REGISTER_NUMBER',
            field=models.CharField(max_length=511),
        ),
    ]
