# Generated by Django 3.0.6 on 2020-06-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_auto_20200604_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='OCENKA_OBESPECHENIYA',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_CRED_SCHET',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_NACH_PRCNT',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_NACH_PROSR_PRCNT',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_PERESM',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_PROSR',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_REZERV',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_SUDEB',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_VNEB_PROSR',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='SUM_DOG_EKV',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='SUM_DOG_NOM',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='VSEGO_ZADOLJENNOST',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
