# Generated by Django 3.0.7 on 2020-07-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0007_auto_20200702_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdata',
            name='REGISTER_NUMBER',
            field=models.CharField(max_length=512),
        ),
    ]
