# Generated by Django 3.0.6 on 2020-06-04 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0008_auto_20200604_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdata',
            name='REPORT_ID',
        ),
        migrations.AddField(
            model_name='reportdata',
            name='REPORT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REPORT', to='credits.ListReports'),
        ),
    ]
