# Generated by Django 3.0.7 on 2020-07-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0009_auto_20200702_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdata',
            name='DATE_SUDEB',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='RAYON_PODACHI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tempdata',
            name='ZARUBEJNIY_BANK',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
