# Generated by Django 3.0.6 on 2020-06-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0010_auto_20200604_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='CODE_CONTRACT',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OCENKA_OBESPECHENIYA',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_CRED_SCHET',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_NACH_PRCNT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_NACH_PROSR_PRCNT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_PERESM',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_PROSR',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_REZERV',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_SUDEB',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='OSTATOK_VNEB_PROSR',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='SUM_DOG_EKV',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='SUM_DOG_NOM',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='VSEGO_ZADOLJENNOST',
            field=models.FloatField(null=True),
        ),
    ]
