# Generated by Django 3.0.7 on 2020-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0010_auto_20200702_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdata',
            name='DATE_SUDEB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='RAYON_PODACHI',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportdata',
            name='ZARUBEJNIY_BANK',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
