# Generated by Django 3.0.6 on 2020-06-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0011_auto_20200604_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=5)),
                ('NAME', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=5)),
                ('NAME', models.CharField(choices=[('ФЛ', 'Физические лица'), ('ЮЛ', 'Юридические лица'), ('ИП', 'Индивидуалные предприятия')], max_length=255)),
                ('SUBJ', models.CharField(choices=[('P', 'P'), ('J', 'J')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='BALANS_SCHET',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
