# Generated by Django 3.0.6 on 2020-06-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0012_auto_20200608_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttype',
            name='NAME',
            field=models.CharField(choices=[('ФЛ', 'Физические лица'), ('ЮЛ', 'Юридические лица'), ('ИП', 'Индивидуалные предприятия')], max_length=2),
        ),
    ]
