# Generated by Django 3.0.7 on 2020-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0012_auto_20200702_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='CLASS_KACHESTVA',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='DATE_PRED_RESH',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='INN_PASSPORT',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='REGISTER_NUMBER',
            field=models.CharField(max_length=1000),
        ),
    ]
