# Generated by Django 3.0.6 on 2020-06-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0013_auto_20200608_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttype',
            name='NAME',
            field=models.CharField(choices=[('ФЛ', 'Физические лица'), ('ЮЛ', 'Юридические лица'), ('ИП', 'Индивидуалные предприятия')], default='ФЛ', max_length=2),
        ),
        migrations.AlterField(
            model_name='clienttype',
            name='SUBJ',
            field=models.CharField(choices=[('P', 'P'), ('J', 'J')], default='P', max_length=1),
        ),
    ]
