# Generated by Django 3.0.7 on 2020-07-08 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0013_auto_20200702_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255, verbose_name='Показатели')),
                ('Old_Value', models.CharField(max_length=255, verbose_name='Предыдущий  месяц')),
                ('New_Value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Текущий месяц')),
                ('Updates', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Изменение')),
                ('Percent', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Изменение, %')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OverduePercents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FilialCode', models.CharField(max_length=5, null=True)),
                ('LoanID', models.IntegerField(null=True)),
                ('AccountCode', models.CharField(max_length=27, null=True)),
                ('SaldoOut', models.FloatField(null=True)),
                ('ArrearDate', models.CharField(max_length=10, null=True)),
                ('DayCount', models.IntegerField(null=True)),
                ('REPORT', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='REPORTDATA', to='credits.ListReports')),
            ],
        ),
    ]
