# Generated by Django 3.0.6 on 2020-06-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0014_auto_20200608_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODE', models.CharField(max_length=3)),
                ('NAME', models.CharField(max_length=3)),
            ],
        ),
    ]
