# Generated by Django 3.0.7 on 2020-07-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0014_infocredits_overduepercents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overduepercents',
            name='ArrearDate',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
