# Generated by Django 3.0.6 on 2020-06-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0016_segment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branches',
            new_name='Branch',
        ),
        migrations.AlterField(
            model_name='segment',
            name='NAME',
            field=models.CharField(choices=[('Прочие', 'Прочие'), ('ФЛ', 'ФЛ'), ('Торговля', 'Торговля'), ('Промышленность', 'Промышленность'), ('Строительство', 'Строительство'), ('Селськое хозяйство', 'Селськое хозяйство'), ('ЖКХ', 'ЖКХ'), ('Транспорт', 'Транспорт'), ('Заготовки', 'Заготовки')], max_length=255),
        ),
    ]
