# Generated by Django 3.0.7 on 2020-07-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0016_auto_20200713_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='byaveragefl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='databygeocode',
            options={'managed': False},
        ),
    ]
