# Generated by Django 3.0.7 on 2020-06-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0017_auto_20200608_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='SORT',
            field=models.IntegerField(null=True),
        ),
    ]
