# Generated by Django 3.0.7 on 2020-06-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0018_branch_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='NplClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(verbose_name='№')),
                ('Name', models.CharField(max_length=255, verbose_name='Наименование заёмщика')),
                ('Branch', models.CharField(max_length=255, verbose_name='Филиал')),
                ('Balans', models.FloatField(verbose_name='Остаток кредита (млн. сум)')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
