# Generated by Django 3.0.7 on 2020-06-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0019_nplclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByTerms',
            fields=[
                ('Group', models.IntegerField(primary_key=True, serialize=False, verbose_name='Группы')),
                ('Title', models.CharField(max_length=255, verbose_name='Сроки')),
                ('PorBalans', models.FloatField(verbose_name='Кредитный портфель')),
                ('NplBalans', models.FloatField(verbose_name='Кредитный портфель')),
                ('ToxBalans', models.FloatField(verbose_name='Кредитный портфель')),
                ('ResBalans', models.FloatField(verbose_name='Кредитный портфель')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OverdueCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(verbose_name='№')),
                ('Name', models.CharField(max_length=255, verbose_name='Наименование клиента')),
                ('Branch', models.CharField(max_length=255, verbose_name='Филиал')),
                ('Balans', models.FloatField(verbose_name='Остаток р/с 16377')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToxicCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(verbose_name='№')),
                ('Name', models.CharField(max_length=255, verbose_name='Наименование клиента')),
                ('Branch', models.CharField(max_length=255, verbose_name='Филиал')),
                ('Balans', models.FloatField(verbose_name='Остаток р/с 16377')),
            ],
            options={
                'managed': False,
            },
        ),
    ]
