# Generated by Django 3.0.7 on 2020-06-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0020_byterms_overduecredits_toxiccredits'),
    ]

    operations = [
        migrations.AddField(
            model_name='listreports',
            name='START_MONTH',
            field=models.DateTimeField(null=True),
        ),
    ]
