# Generated by Django 3.0.7 on 2020-06-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0021_listreports_start_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=255, verbose_name='№')),
                ('Title', models.CharField(max_length=255, verbose_name='Коридор')),
                ('ULLongTerm', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Долгосрочные ЮЛ')),
                ('ULLongPart', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Доля, %')),
                ('ULShortTerm', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Краткосрочные ЮЛ')),
                ('ULShortPart', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Доля, %')),
                ('FLLongTerm', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Долгосрочные ФЛ')),
                ('FLLongPart', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Доля, %')),
                ('FLShortTerm', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Краткосрочные ФЛ')),
                ('FLShortPart', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Доля, %')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ByPercentageUL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=255, verbose_name='№')),
                ('Title', models.CharField(max_length=255, verbose_name='Коридор')),
                ('Term1', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='до 2-х лет')),
                ('Term2', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='от 2-х до 5 лет')),
                ('Term3', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='от 5-ти до 7 лет')),
                ('Term4', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='от 7-ми до 10 лет')),
                ('Term5', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='свыше 10 лет')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ByRetailProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=255, verbose_name='№')),
                ('Title', models.CharField(max_length=255, verbose_name='Продукт')),
                ('PorBalans', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Кредитный портфель')),
                ('PorPercent', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Доля, %')),
                ('PrsBalans', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Просрочка ОД')),
                ('NplBalans', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='NPL')),
                ('NplWeight', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Удельный вес')),
                ('NachBalans', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Просрочка по % (16377)')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='branch',
            name='CODE',
            field=models.CharField(db_index=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='clienttype',
            name='CODE',
            field=models.CharField(db_index=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='CODE',
            field=models.CharField(db_index=True, max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='CODE',
            field=models.CharField(db_index=True, max_length=2, unique=True),
        ),
    ]
