# Generated by Django 3.0.7 on 2020-06-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0024_auto_20200625_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienttype',
            name='CODE',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='currency',
            name='CODE',
            field=models.CharField(db_index=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='segment',
            name='CODE',
            field=models.CharField(db_index=True, max_length=2),
        ),
    ]
