# Generated by Django 3.0.7 on 2020-06-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0025_auto_20200625_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='GEOCODE',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
