from django.db import models

# Create your models here.
class ListReports(models.Model):
    REPORT_TITLE = models.CharField(max_length=255)
    REPORT_MONTH = models.IntegerField()
    REPORT_YEAR  = models.IntegerField()
    DATE_CREATED = models.DateTimeField(null=True)
class ReportData(models.Model):
    REPORT = models.ForeignKey(ListReports, on_delete=models.CASCADE, default=None)
    NUMBER                  = models.IntegerField()
    CODE_REG                = models.CharField(max_length=25)
    MFO                     = models.CharField(max_length=5)
    NAME_CLIENT             = models.CharField(max_length=255)
    BALANS_SCHET            = models.IntegerField()
    CREDIT_SCHET            = models.CharField(max_length=20)
    DATE_RESHENIYA          = models.CharField(max_length=25)
    CODE_VAL                = models.CharField(max_length=25)
    SUM_DOG_NOM             = models.DecimalField(max_digits=15, decimal_places=2)
    SUM_DOG_EKV             = models.DecimalField(max_digits=15, decimal_places=2)
    DATE_DOGOVOR            = models.DateField()
    DATE_FACTUAL            = models.DateField()
    DATE_POGASH             = models.DateField()
    SROK                    = models.CharField(max_length=25)
    DOG_NUMBER_DATE         = models.CharField(max_length=25)
    CREDIT_PROCENT          = models.IntegerField()
    PROSR_PROCENT           = models.IntegerField()
    OSTATOK_CRED_SCHET      = models.DecimalField(max_digits=15, decimal_places=2)
    OSTATOK_PERESM          = models.DecimalField(max_digits=15, decimal_places=2)
    DATE_PRODL              = models.CharField(max_length=25)
    DATE_POGASH_POSLE_PRODL = models.DateField()
    OSTATOK_PROSR           = models.DecimalField(max_digits=15, decimal_places=2)
    DATE_OBRAZ_PROS         = models.DateField()
    OSTATOK_SUDEB           = models.DecimalField(max_digits=15, decimal_places=2)
    KOD_PRAVOXR_ORG         = models.CharField(max_length=255)
    PRIZNAK_RESHENIYA       = models.CharField(max_length=255)
    DATE_PRED_RESH          = models.CharField(max_length=25)
    VSEGO_ZADOLJENNOST      = models.DecimalField(max_digits=15, decimal_places=2)
    CLASS_KACHESTVA         = models.CharField(max_length=25)
    OSTATOK_REZERV          = models.DecimalField(max_digits=15, decimal_places=2)
    OSTATOK_NACH_PRCNT      = models.DecimalField(max_digits=15, decimal_places=2)
    OSTATOK_NACH_PROSR_PRCNT= models.DecimalField(max_digits=15, decimal_places=2)
    OCENKA_OBESPECHENIYA    = models.DecimalField(max_digits=15, decimal_places=2)
    OBESPECHENIE            = models.CharField(max_length=255)
    OPISANIE_OBESPECHENIE   = models.CharField(max_length=255)
    ISTOCHNIK_SREDTSVO      = models.CharField(max_length=255)
    VID_KREDITOVANIYA       = models.CharField(max_length=255)
    PURPOSE_CREDIT          = models.CharField(max_length=255)
    VISHEST_ORG_CLIENT      = models.CharField(max_length=255)
    OTRASL_KREDITOVANIYA    = models.CharField(max_length=255)
    OTRASL_CLIENTA          = models.CharField(max_length=255)
    CLASS_KREDIT_SPOS       = models.CharField(max_length=255)
    PREDSEDATEL_KB          = models.CharField(max_length=255)
    ADRESS_CLIENT           = models.CharField(max_length=255)
    UN_NUMBER_CONTRACT      = models.CharField(max_length=255)
    INN_PASSPORT            = models.CharField(max_length=25)
    OSTATOK_VNEB_PROSR      = models.DecimalField(max_digits=15, decimal_places=2)
    KONKR_NAZN_CREDIT       = models.CharField(max_length=255)
    BORROWER_TYPE           = models.CharField(max_length=255)
    SVYAZANNIY              = models.IntegerField()
    MALIY_BIZNES            = models.IntegerField()
    REGISTER_NUMBER         = models.CharField(max_length=255)
    OKED                    = models.CharField(max_length=255)
    CODE_CONRACT            = models.CharField(max_length=25)